name = "AsmMacro"
uuid = "6f2a8737-d8b6-455e-b4f3-8201eec06ac4"
authors = ["Yingbo Ma <mayingbo5@gmail.com>"]
version = "0.1.0"

[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
